# Corpus Embedding and Indexing Demo

# MCP Server
servers:
  retriever: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/retriever

# MCP Client Pipeline
pipeline:
- retriever.retriever_init
- retriever.retriever_embed
- retriever.retriever_index
