# IRCoT Demo

# MCP Server
servers:
  benchmark: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/benchmark
  generation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/generation
  retriever: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/retriever
  prompt: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/prompt
  evaluation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/evaluation
  router: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/router
  custom: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/custom

# MCP Client Pipeline
pipeline:
- benchmark.get_data
- retriever.retriever_init
- generation.generation_init
- loop:
    times: 2
    steps:
    - retriever.retriever_search
    - prompt.ircot_next_prompt
    - generation.generate
    - branch:
        router:
        - router.ircot_check_end
        branches:
          incomplete:
          - custom.ircot_get_first_sent
          complete: []
- retriever.retriever_search
- prompt.ircot_next_prompt
- generation.generate
- custom.ircot_extract_ans
- evaluation.evaluate
