# LLM Demo for UltraRAG UI

# MCP Server
servers:
  benchmark: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/benchmark
  prompt: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/prompt
  generation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/generation

# MCP Client Pipeline
pipeline:
- benchmark.get_data
- prompt.qa_boxed
- generation.generation_init
- generation.generate
