# RAG Demo for UltraRAG UI

# MCP Server
servers:
  benchmark: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/benchmark
  retriever: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/retriever
  prompt: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/prompt
  generation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/generation
  evaluation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/evaluation
  custom: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/custom

# MCP Client Pipeline
pipeline:
- benchmark.get_data
- retriever.retriever_init
- generation.generation_init
- retriever.retriever_websearch
- custom.assign_citation_ids
- prompt.qa_rag_boxed
- generation.generate
