# RankCoT Demo

# MCP Server
servers:
  benchmark: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/benchmark
  retriever: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/retriever
  prompt: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/prompt
  cot: servers/generation
  gen: servers/generation
  evaluation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/evaluation

# MCP Client Pipeline
pipeline:
- benchmark.get_data
- retriever.retriever_init
- retriever.retriever_search
- prompt.RankCoT_kr
- cot.generation_init
- gen.generation_init
- cot.generate:
    output:
      ans_ls: kr_ls
- prompt.RankCoT_qa

- gen.generate
- evaluation.evaluate:
    input:
      pred_ls: ans_ls
