# Search-R1 Demo

# MCP Server
servers:
  benchmark: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/benchmark
  generation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/generation
  retriever: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/retriever
  prompt: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/prompt
  evaluation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/evaluation
  router: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/router
  custom: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/custom

# MCP Client Pipeline
pipeline:
- benchmark.get_data
- retriever.retriever_init
- generation.generation_init
- prompt.qa_boxed
- generation.generate
- loop:
    times: 5
    steps:
    - branch:
        router:
        - router.search_r1_check
        branches:
          incomplete:
          - custom.search_r1_query_extract
          - retriever.retriever_search:
              input:
                query_list: extract_query_list
          - prompt.search_r1_gen
          - generation.generate
          complete: []
- evaluation.evaluate:
    input:
      pred_ls: ans_ls
