# Vanilla LLM Demo for Multiple Choice Dataset

# MCP Server
servers:
  benchmark: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/benchmark
  prompt: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/prompt
  generation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/generation
  evaluation: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/evaluation
  custom: D:/华南理工大学/软件工程概论/contract_revision_agent/UltraRAG/servers/custom

# MCP Client Pipeline
pipeline:
- benchmark.get_data
- generation.generation_init
- prompt.qa_boxed_multiple_choice
- generation.generate
- custom.output_extract_from_boxed
- evaluation.evaluate
